
###

# CRIA UM LEILÃO
POST http://localhost:3003/Auction
Content-Type: application/json

{
    "title":"test art3",
    "initialValue":3000,
    "bidProgression":200,
    "expirationDate":"2021-08-22"
}

###

# CRIA UM LANCE
POST http://localhost:3003/Auction/bid
Content-Type: application/json

{
    "name":"Jonny Pey",
    "value":3400,
    "auction_id":3
}

###
# RETORNA UM ARRAY C/ TODOS OS LEILÕES
GET http://localhost:3003/Auction/


###
# RETORNA UM ARRAY C/ TODOS OS LANCES
GET http://localhost:3003/Auction/bid


###
# RETORNA OS DETALHES DE 1 LEILÃO C/ 
# TODOS OS DADOS + DIAS PARA EXPIRAR + ARRAY DE LANCES

GET http://localhost:3003/Auction/3

###
