
###

# CRIA UM LEILÃO
POST http://localhost:3001/Auction
Content-Type: application/json

{
    "title":" crazy green art ",
    "initialValue":1500,
    "bidProgression":50,
    "expirationDate":"2021-07-02"
}

###

# CRIA UM LANCE
POST http://localhost:3001/Auction/bid
Content-Type: application/json

{
    "name":"Kell Lanes",
    "value":3600,
    "auction_id":1
}

###
# RETORNA UM ARRAY C/ TODOS OS LEILÕES
GET http://localhost:3001/Auction/


###
# RETORNA UM ARRAY C/ TODOS OS LANCES
GET http://localhost:3001/Auction/bid


###
# RETORNA OS DETALHES DE 1 LEILÃO C/ 
# TODOS OS DADOS + DIAS PARA EXPIRAR + ARRAY DE LANCES

GET http://localhost:3001/Auction/1

###
